// Maintainer-only: generated runtime sources are committed; users need no build step.
import {readFileSync,writeFileSync} from 'node:fs'
const root=new URL('../',import.meta.url)
const strings=JSON.parse(readFileSync(new URL('macos/assets/ui-strings.json',root),'utf8'))
if(!Object.entries(strings).every(([k,v])=>k&&typeof v==='string'&&v&&JSON.stringify(k.match(/\{\d+\}/g)?.sort()||[])===JSON.stringify(v.match(/\{\d+\}/g)?.sort()||[])))throw Error('Invalid localization catalog or placeholders')
const clientPath=new URL('lib/client.js',root),client=readFileSync(clientPath,'utf8')
const next=client.replace(/(\/\/ UI_LOCALES_START[^\n]*\n)[\s\S]*?(    \/\/ UI_LOCALES_END)/,(_,a,b)=>a+'    var uiStrings = '+JSON.stringify(strings)+';\n'+b)
const swift='// Generated by scripts/sync-locales.mjs; edit macos/assets/ui-strings.json.\nimport Foundation\nlet uiEnglish: [String:String] = [\n'+Object.entries(strings).map(([k,v])=>' '+JSON.stringify(k)+':'+JSON.stringify(v)).join(',\n')+'\n]\n'
for(const [path,content] of [[clientPath,next],[new URL('macos/UIStrings.swift',root),swift]]) {
 if(process.argv.includes('--check')) {if(readFileSync(path,'utf8')!==content)throw Error('Generated locale source is stale: '+path)}else writeFileSync(path,content)
}
console.log('Localization catalog synchronized: '+Object.keys(strings).length+' messages')
